apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  generators:
  - list:
      elements:
      - cluster: in-cluster
        serverName: https://kubernetes.default.svc
        namespace: default
        appName: 
      - cluster: gke-c2
        serverName: https://34.31.156.179
        namespace: sourabh
        appName: 
      - cluster: in-cluster
        serverName: https://kubernetes.default.svc
        namespace: default
        appName: 
      - cluster: gke-c2
        serverName: https://34.31.156.179
        namespace: sourabh
        appName: 
      - cluster: in-cluster
        serverName: https://kubernetes.default.svc
        namespace: default
        appName: 
      - cluster: gke-c2
        serverName: https://34.31.156.179
        namespace: sourabh
      
  template:
    metadata:
      name: "{{appName}}"
      annotations:
        argocd.argoproj.io/manifest-generate-paths: ".;.."
    spec:
      project: default
      source:
        repoURL: https://github.com/JulienJourdain/infrastructure.git
        targetRevision: HEAD
        path: "kubernetes/resources/{{appName}}"
        helm:
          # Release name override (defaults to application name)
          releaseName: "{{appName}}"
          valueFiles:
          - values.yaml
      destination:
        server: in-cluster
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true