apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  generators:
  - list:
      elements:
      - cluster: in-cluster
        serverName: https://kubernetes.default.svc
        namespace: default
        appName: blue-green
      - cluster: gke-c2
        serverName: https://34.31.156.179
        namespace: sourabh
        appName: guestbook
      - cluster: in-cluster
        serverName: https://kubernetes.default.svc
        namespace: default
        appName: helm-guestbook
      - cluster: gke-c2
        serverName: https://34.31.156.179
        namespace: sourabh
        appName: jsonnet-guestbook
      - cluster: in-cluster
        serverName: https://kubernetes.default.svc
        namespace: default
        appName: jsonnet-guestbook-tla
      - cluster: gke-c2
        serverName: https://34.31.156.179
        namespace: sourabh
        appName: ksonnet-guestbook
      - cluster: in-cluster
        serverName: https://kubernetes.default.svc
        namespace: default
        appName: kustomize-guestbook
      - cluster: gke-c2
        serverName: https://34.31.156.179
        namespace: sourabh
        appName: pre-post-sync
      
  template:
    metadata:
      name: "{{appName}}"
    spec:
      project: default
      source:
        repoURL: git@github.com:code-sourabh/argo-cluster.git
        targetRevision: HEAD
        path: "kubernetes/resources/{{appName}}"
        helm:
          # Release name override (defaults to application name)
          releaseName: "{{appName}}"
          valueFiles:
          - values.yaml
      destination:
        server: in-cluster
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true